services:
  cinema-database:
    environment:
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_pass
      POSTGRES_DB: cinema_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data